"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from shippo.types import BaseModel
import shippo.utils as utils
from typing import Optional

class InitiateOauth2SigninCarrierAccountsResponseBodyData(BaseModel):
    title: Optional[str] = None
    detail: Optional[str] = None
    


class InitiateOauth2SigninCarrierAccountsResponseBody(Exception):
    r"""Invalid carrier account provided by the user"""
    data: InitiateOauth2SigninCarrierAccountsResponseBodyData

    def __init__(self, data: InitiateOauth2SigninCarrierAccountsResponseBodyData):
        self.data = data

    def __str__(self) -> str:
        return utils.marshal_json(self.data, InitiateOauth2SigninCarrierAccountsResponseBodyData)

class InitiateOauth2SigninCarrierAccountsResponseResponseBodyData(BaseModel):
    title: Optional[str] = None
    detail: Optional[str] = None
    


class InitiateOauth2SigninCarrierAccountsResponseResponseBody(Exception):
    r"""Invalid ShippoToken or unsupported carrier account provided by the user"""
    data: InitiateOauth2SigninCarrierAccountsResponseResponseBodyData

    def __init__(self, data: InitiateOauth2SigninCarrierAccountsResponseResponseBodyData):
        self.data = data

    def __str__(self) -> str:
        return utils.marshal_json(self.data, InitiateOauth2SigninCarrierAccountsResponseResponseBodyData)

class InitiateOauth2SigninResponseBodyData(BaseModel):
    title: Optional[str] = None
    detail: Optional[str] = None
    


class InitiateOauth2SigninResponseBody(Exception):
    r"""Invalid parameters provided by the user"""
    data: InitiateOauth2SigninResponseBodyData

    def __init__(self, data: InitiateOauth2SigninResponseBodyData):
        self.data = data

    def __str__(self) -> str:
        return utils.marshal_json(self.data, InitiateOauth2SigninResponseBodyData)

