"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

import importlib.metadata

__title__: str = "shippo"
__version__: str = "4.2.6"
__openapi_doc_version__: str = "2018-02-08"
__gen_version__: str = "2.545.7"
__user_agent__: str = "speakeasy-sdk/python 4.2.6 2.545.7 2018-02-08 shippo"

try:
    if __package__ is not None:
        __version__ = importlib.metadata.version(__package__)
except importlib.metadata.PackageNotFoundError:
    pass
