"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .basesdk import BaseSDK
from shippo import utils
from shippo._hooks import HookContext
from shippo.models import components, errors, operations
from shippo.types import OptionalNullable, UNSET
from shippo.utils.unmarshal_json_response import unmarshal_json_response
from typing import Mapping, Optional, Union


class EmbeddedAuthorization(BaseSDK):
    r"""Mint short-lived JSON Web Tokens (JWTs) for client-side applications, so you never ship a
    long-lived API token to the browser. Authenticate the request with a Shippo API token or an
    OAuth bearer token, then pass the returned token as `Authorization: JWT <JWT_TOKEN>`.
    See our [Authentication using JWT guide](https://docs.goshippo.com/docs/guides_general/authentication_using_jwt/) for details.
    """

    def create(
        self,
        *,
        security: Union[
            operations.CreateEmbeddedAuthorizationSecurity,
            operations.CreateEmbeddedAuthorizationSecurityTypedDict,
        ],
        embedded_authorization_request: Union[
            components.EmbeddedAuthorizationRequest,
            components.EmbeddedAuthorizationRequestTypedDict,
        ],
        shippo_account_id: Optional[str] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> components.EmbeddedAuthorization:
        r"""Create a JWT

        Creates a short-lived JSON Web Token (JWT) that client-side applications can use
        to authenticate against the Shippo API without exposing a long-lived API token.

        Authenticate this request with either a Shippo API token
        (`Authorization: ShippoToken <API_TOKEN>`) or an OAuth bearer token
        (`Authorization: Bearer <OAUTH_BEARER_TOKEN>`). Platform accounts can mint a token
        on behalf of a Managed Shippo Account by setting the `SHIPPO-ACCOUNT-ID` header.

        The returned token is valid for 12 hours. Send it on subsequent requests as
        `Authorization: JWT <JWT_TOKEN>`.

        :param security:
        :param embedded_authorization_request: The scope to request for the token.
        :param shippo_account_id: Optional. The object ID of a Managed Shippo Account. Platform accounts set this to
            mint a JWT scoped to one of their managed accounts.
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = operations.CreateEmbeddedAuthorizationRequest(
            shippo_account_id=shippo_account_id,
            embedded_authorization_request=utils.get_pydantic_model(
                embedded_authorization_request, components.EmbeddedAuthorizationRequest
            ),
        )

        req = self._build_request(
            method="POST",
            path="/embedded/authz",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            _globals=operations.CreateEmbeddedAuthorizationGlobals(
                shippo_api_version=self.sdk_configuration.globals.shippo_api_version,
            ),
            security=utils.get_pydantic_model(
                security, operations.CreateEmbeddedAuthorizationSecurity
            ),
            get_serialized_body=lambda: utils.serialize_request_body(
                request.embedded_authorization_request,
                False,
                False,
                "json",
                components.EmbeddedAuthorizationRequest,
            ),
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="CreateEmbeddedAuthorization",
                oauth2_scopes=None,
                security_source=security,
                tags=["Embedded Authorization"],
                extensions={
                    "x-codeSamples": [
                        {
                            "label": "cURL",
                            "lang": "cURL",
                            "source": 'curl https://api.goshippo.com/embedded/authz \\\n  -H "Authorization: ShippoToken <API_TOKEN>" \\\n  -H "Content-Type: application/json" \\\n  --data-raw \'{\n      "scope": "embedded:carriers"\n  }\'',
                        }
                    ]
                },
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(components.EmbeddedAuthorization, http_res)
        if utils.match_response(http_res, ["400", "4XX"], "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.SDKError("API error occurred", http_res, http_res_text)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.SDKError("API error occurred", http_res, http_res_text)

        raise errors.SDKError("Unexpected response received", http_res)

    async def create_async(
        self,
        *,
        security: Union[
            operations.CreateEmbeddedAuthorizationSecurity,
            operations.CreateEmbeddedAuthorizationSecurityTypedDict,
        ],
        embedded_authorization_request: Union[
            components.EmbeddedAuthorizationRequest,
            components.EmbeddedAuthorizationRequestTypedDict,
        ],
        shippo_account_id: Optional[str] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> components.EmbeddedAuthorization:
        r"""Create a JWT

        Creates a short-lived JSON Web Token (JWT) that client-side applications can use
        to authenticate against the Shippo API without exposing a long-lived API token.

        Authenticate this request with either a Shippo API token
        (`Authorization: ShippoToken <API_TOKEN>`) or an OAuth bearer token
        (`Authorization: Bearer <OAUTH_BEARER_TOKEN>`). Platform accounts can mint a token
        on behalf of a Managed Shippo Account by setting the `SHIPPO-ACCOUNT-ID` header.

        The returned token is valid for 12 hours. Send it on subsequent requests as
        `Authorization: JWT <JWT_TOKEN>`.

        :param security:
        :param embedded_authorization_request: The scope to request for the token.
        :param shippo_account_id: Optional. The object ID of a Managed Shippo Account. Platform accounts set this to
            mint a JWT scoped to one of their managed accounts.
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = operations.CreateEmbeddedAuthorizationRequest(
            shippo_account_id=shippo_account_id,
            embedded_authorization_request=utils.get_pydantic_model(
                embedded_authorization_request, components.EmbeddedAuthorizationRequest
            ),
        )

        req = self._build_request_async(
            method="POST",
            path="/embedded/authz",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            _globals=operations.CreateEmbeddedAuthorizationGlobals(
                shippo_api_version=self.sdk_configuration.globals.shippo_api_version,
            ),
            security=utils.get_pydantic_model(
                security, operations.CreateEmbeddedAuthorizationSecurity
            ),
            get_serialized_body=lambda: utils.serialize_request_body(
                request.embedded_authorization_request,
                False,
                False,
                "json",
                components.EmbeddedAuthorizationRequest,
            ),
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="CreateEmbeddedAuthorization",
                oauth2_scopes=None,
                security_source=security,
                tags=["Embedded Authorization"],
                extensions={
                    "x-codeSamples": [
                        {
                            "label": "cURL",
                            "lang": "cURL",
                            "source": 'curl https://api.goshippo.com/embedded/authz \\\n  -H "Authorization: ShippoToken <API_TOKEN>" \\\n  -H "Content-Type: application/json" \\\n  --data-raw \'{\n      "scope": "embedded:carriers"\n  }\'',
                        }
                    ]
                },
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(components.EmbeddedAuthorization, http_res)
        if utils.match_response(http_res, ["400", "4XX"], "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.SDKError("API error occurred", http_res, http_res_text)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.SDKError("API error occurred", http_res, http_res_text)

        raise errors.SDKError("Unexpected response received", http_res)
