"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .basesdk import BaseSDK
from shippo import utils
from shippo._hooks import HookContext
from shippo.models import components, errors, operations
from shippo.types import BaseModel, OptionalNullable, UNSET
from shippo.utils.unmarshal_json_response import unmarshal_json_response
from typing import Mapping, Optional, Union, cast


class UserParcelTemplates(BaseSDK):
    r"""A user parcel template represents a package used for shipping that has preset dimensions and attributes defined
    by you. They are useful for capturing attributes of parcel-types you frequently use for shipping, allowing
    them to be defined once and then used for many shipments. These parcel templates can also be used for live rates.

    User parcel templates can also be created using a carrier parcel template, where the dimensions will be copied from
    the carrier presets, but the weight can be configured by you.
    """

    def list(
        self,
        *,
        request: Union[
            operations.ListUserParcelTemplatesRequest,
            operations.ListUserParcelTemplatesRequestTypedDict,
        ],
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> components.UserParcelTemplateList:
        r"""List all user parcel templates

        Returns a list all of all user parcel template objects.

        :param request: The request object to send.
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        if not isinstance(request, BaseModel):
            request = utils.unmarshal(
                request, operations.ListUserParcelTemplatesRequest
            )
        request = cast(operations.ListUserParcelTemplatesRequest, request)

        req = self._build_request(
            method="GET",
            path="/user-parcel-templates",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            _globals=operations.ListUserParcelTemplatesGlobals(
                shippo_api_version=self.sdk_configuration.globals.shippo_api_version,
            ),
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="ListUserParcelTemplates",
                oauth2_scopes=None,
                security_source=self.sdk_configuration.security,
                tags=["User Parcel Templates"],
                extensions={
                    "x-codeSamples": [
                        {
                            "label": "cURL",
                            "lang": "cURL",
                            "source": 'curl https://api.goshippo.com/user-parcel-templates  \\\n-H "Authorization: ShippoToken <API_TOKEN>" \\\n-H "Content-Type: application/json"',
                        },
                        {
                            "label": "Python",
                            "lang": "python",
                            "source": "import shippo\nfrom shippo.models import operations\n\ns = shippo.Shippo(\n    api_key_header='ShippoToken <API_TOKEN>',\n    shippo_api_version='2018-02-08',\n)\n\n\nres = s.user_parcel_templates.list(request=operations.ListUserParcelTemplatesRequest())\n\nif res is not None:\n    # handle response\n    pass",
                        },
                        {
                            "label": "Typescript",
                            "lang": "typescript",
                            "source": 'import { Shippo } from "shippo";\n\nconst shippo = new Shippo({\n  apiKeyHeader: "ShippoToken <API_TOKEN>",\n  shippoApiVersion: "2018-02-08",\n});\n\nasync function run() {\n  const result = await shippo.userParcelTemplates.list({});\n\n  // Handle the result\n  console.log(result);\n}\n\nrun();',
                        },
                        {
                            "label": "C#",
                            "lang": "csharp",
                            "source": 'using Shippo;\nusing Shippo.Models.Components;\n\nvar sdk = new ShippoSDK(\n    apiKeyHeader: "ShippoToken <API_TOKEN>",\n    shippoApiVersion: "2018-02-08"\n);\n\nvar res = await sdk.UserParcelTemplates.ListAsync(shippoApiVersion: "2018-02-08");\n\n// handle response',
                        },
                        {
                            "label": "PHP",
                            "lang": "php",
                            "source": "declare(strict_types=1);\n\nrequire 'vendor/autoload.php';\n\nuse Shippo\\API;\n\n$sdk = API\\Shippo::builder()\n    ->setSecurity(\n        'ShippoToken <API_TOKEN>'\n    )\n    ->setShippoApiVersion('2018-02-08')\n    ->build();\n\n\n\n$response = $sdk->userParcelTemplates->list(\n    shippoApiVersion: '2018-02-08'\n);\n\nif ($response->userParcelTemplateList !== null) {\n    // handle response\n}",
                        },
                        {
                            "label": "Java",
                            "lang": "java",
                            "source": 'package hello.world;\n\nimport com.goshippo.shippo_sdk.Shippo;\nimport com.goshippo.shippo_sdk.models.operations.ListUserParcelTemplatesResponse;\nimport java.lang.Exception;\n\npublic class Application {\n\n    public static void main(String[] args) throws Exception {\n\n        Shippo sdk = Shippo.builder()\n                .apiKeyHeader("ShippoToken <API_TOKEN>")\n                .shippoApiVersion("2018-02-08")\n            .build();\n\n        ListUserParcelTemplatesResponse res = sdk.userParcelTemplates().list()\n                .shippoApiVersion("2018-02-08")\n                .call();\n\n        if (res.userParcelTemplateList().isPresent()) {\n            // handle response\n        }\n    }\n}',
                        },
                    ]
                },
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(components.UserParcelTemplateList, http_res)
        if utils.match_response(http_res, ["400", "4XX"], "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.SDKError("API error occurred", http_res, http_res_text)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.SDKError("API error occurred", http_res, http_res_text)

        raise errors.SDKError("Unexpected response received", http_res)

    async def list_async(
        self,
        *,
        request: Union[
            operations.ListUserParcelTemplatesRequest,
            operations.ListUserParcelTemplatesRequestTypedDict,
        ],
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> components.UserParcelTemplateList:
        r"""List all user parcel templates

        Returns a list all of all user parcel template objects.

        :param request: The request object to send.
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        if not isinstance(request, BaseModel):
            request = utils.unmarshal(
                request, operations.ListUserParcelTemplatesRequest
            )
        request = cast(operations.ListUserParcelTemplatesRequest, request)

        req = self._build_request_async(
            method="GET",
            path="/user-parcel-templates",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            _globals=operations.ListUserParcelTemplatesGlobals(
                shippo_api_version=self.sdk_configuration.globals.shippo_api_version,
            ),
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="ListUserParcelTemplates",
                oauth2_scopes=None,
                security_source=self.sdk_configuration.security,
                tags=["User Parcel Templates"],
                extensions={
                    "x-codeSamples": [
                        {
                            "label": "cURL",
                            "lang": "cURL",
                            "source": 'curl https://api.goshippo.com/user-parcel-templates  \\\n-H "Authorization: ShippoToken <API_TOKEN>" \\\n-H "Content-Type: application/json"',
                        },
                        {
                            "label": "Python",
                            "lang": "python",
                            "source": "import shippo\nfrom shippo.models import operations\n\ns = shippo.Shippo(\n    api_key_header='ShippoToken <API_TOKEN>',\n    shippo_api_version='2018-02-08',\n)\n\n\nres = s.user_parcel_templates.list(request=operations.ListUserParcelTemplatesRequest())\n\nif res is not None:\n    # handle response\n    pass",
                        },
                        {
                            "label": "Typescript",
                            "lang": "typescript",
                            "source": 'import { Shippo } from "shippo";\n\nconst shippo = new Shippo({\n  apiKeyHeader: "ShippoToken <API_TOKEN>",\n  shippoApiVersion: "2018-02-08",\n});\n\nasync function run() {\n  const result = await shippo.userParcelTemplates.list({});\n\n  // Handle the result\n  console.log(result);\n}\n\nrun();',
                        },
                        {
                            "label": "C#",
                            "lang": "csharp",
                            "source": 'using Shippo;\nusing Shippo.Models.Components;\n\nvar sdk = new ShippoSDK(\n    apiKeyHeader: "ShippoToken <API_TOKEN>",\n    shippoApiVersion: "2018-02-08"\n);\n\nvar res = await sdk.UserParcelTemplates.ListAsync(shippoApiVersion: "2018-02-08");\n\n// handle response',
                        },
                        {
                            "label": "PHP",
                            "lang": "php",
                            "source": "declare(strict_types=1);\n\nrequire 'vendor/autoload.php';\n\nuse Shippo\\API;\n\n$sdk = API\\Shippo::builder()\n    ->setSecurity(\n        'ShippoToken <API_TOKEN>'\n    )\n    ->setShippoApiVersion('2018-02-08')\n    ->build();\n\n\n\n$response = $sdk->userParcelTemplates->list(\n    shippoApiVersion: '2018-02-08'\n);\n\nif ($response->userParcelTemplateList !== null) {\n    // handle response\n}",
                        },
                        {
                            "label": "Java",
                            "lang": "java",
                            "source": 'package hello.world;\n\nimport com.goshippo.shippo_sdk.Shippo;\nimport com.goshippo.shippo_sdk.models.operations.ListUserParcelTemplatesResponse;\nimport java.lang.Exception;\n\npublic class Application {\n\n    public static void main(String[] args) throws Exception {\n\n        Shippo sdk = Shippo.builder()\n                .apiKeyHeader("ShippoToken <API_TOKEN>")\n                .shippoApiVersion("2018-02-08")\n            .build();\n\n        ListUserParcelTemplatesResponse res = sdk.userParcelTemplates().list()\n                .shippoApiVersion("2018-02-08")\n                .call();\n\n        if (res.userParcelTemplateList().isPresent()) {\n            // handle response\n        }\n    }\n}',
                        },
                    ]
                },
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(components.UserParcelTemplateList, http_res)
        if utils.match_response(http_res, ["400", "4XX"], "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.SDKError("API error occurred", http_res, http_res_text)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.SDKError("API error occurred", http_res, http_res_text)

        raise errors.SDKError("Unexpected response received", http_res)

    def create(
        self,
        *,
        request: Union[
            components.UserParcelTemplateCreateRequest,
            components.UserParcelTemplateCreateRequestTypedDict,
        ],
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> components.UserParcelTemplate:
        r"""Create a new user parcel template

        Creates a new user parcel template.

        You can choose to create a
        parcel template using a preset carrier template as a starting point, or
        you can create an entirely custom one. To use a preset carrier template,
        pass in a unique template token from [this list](/shippoapi/public-api/parcel-templates)
        plus the weight fields (**weight** and **weight_unit**). Otherwise, omit
        the template field and pass the other fields, for the weight, length, height,
        and depth, as well as their units.\"

        :param request: The request object to send.
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        if not isinstance(request, BaseModel):
            request = utils.unmarshal(
                request, components.UserParcelTemplateCreateRequest
            )
        request = cast(components.UserParcelTemplateCreateRequest, request)

        req = self._build_request(
            method="POST",
            path="/user-parcel-templates",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            _globals=operations.CreateUserParcelTemplateGlobals(
                shippo_api_version=self.sdk_configuration.globals.shippo_api_version,
            ),
            security=self.sdk_configuration.security,
            get_serialized_body=lambda: utils.serialize_request_body(
                request,
                False,
                False,
                "json",
                components.UserParcelTemplateCreateRequest,
            ),
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="CreateUserParcelTemplate",
                oauth2_scopes=None,
                security_source=self.sdk_configuration.security,
                tags=["User Parcel Templates"],
                extensions={
                    "x-codeSamples": [
                        {
                            "label": "cURL",
                            "lang": "cURL",
                            "source": 'curl -X POST https://api.goshippo.com/user-parcel-templates  \\\n  -H "Authorization: ShippoToken <API_TOKEN>" \\\n  -H "Content-Type: application/json"\n  -d \'{\n      "name": "My Custom Template",\n      "length": "10",\n      "width": "8",\n      "height": "6",\n      "distance_unit": "in",\n      "weight": "12",\n      "weight_unit": "lb"\n  }\'',
                        },
                        {
                            "label": "Python",
                            "lang": "python",
                            "source": "import shippo\nfrom shippo.models import components\n\ns = shippo.Shippo(\n    api_key_header='ShippoToken <API_TOKEN>',\n    shippo_api_version='2018-02-08',\n)\n\n\nres = s.user_parcel_templates.create(request=components.UserParcelTemplateWithCarrierTemplateCreateRequest(\n    weight='12',\n    weight_unit=components.WeightUnitEnum.LB,\n))\n\nif res is not None:\n    # handle response\n    pass",
                        },
                        {
                            "label": "Typescript",
                            "lang": "typescript",
                            "source": 'import { Shippo } from "shippo";\n\nconst shippo = new Shippo({\n  apiKeyHeader: "ShippoToken <API_TOKEN>",\n  shippoApiVersion: "2018-02-08",\n});\n\nasync function run() {\n  const result = await shippo.userParcelTemplates.create({\n    weight: "12",\n    weightUnit: "lb",\n  });\n\n  // Handle the result\n  console.log(result);\n}\n\nrun();',
                        },
                        {
                            "label": "C#",
                            "lang": "csharp",
                            "source": 'using Shippo;\nusing Shippo.Models.Components;\n\nvar sdk = new ShippoSDK(\n    apiKeyHeader: "ShippoToken <API_TOKEN>",\n    shippoApiVersion: "2018-02-08"\n);\n\nvar res = await sdk.UserParcelTemplates.CreateAsync(\n    userParcelTemplateCreateRequest: UserParcelTemplateCreateRequest.CreateUserParcelTemplateWithCarrierTemplateCreateRequest(\n        new UserParcelTemplateWithCarrierTemplateCreateRequest() {\n            Weight = "12",\n            WeightUnit = WeightUnitEnum.Lb,\n        }\n    ),\n    shippoApiVersion: "2018-02-08"\n);\n\n// handle response',
                        },
                        {
                            "label": "PHP",
                            "lang": "php",
                            "source": "declare(strict_types=1);\n\nrequire 'vendor/autoload.php';\n\nuse Shippo\\API;\nuse Shippo\\API\\Models\\Components;\n\n$sdk = API\\Shippo::builder()\n    ->setSecurity(\n        'ShippoToken <API_TOKEN>'\n    )\n    ->setShippoApiVersion('2018-02-08')\n    ->build();\n\n\n\n$response = $sdk->userParcelTemplates->create(\n    userParcelTemplateCreateRequest: new Components\\UserParcelTemplateWithCarrierTemplateCreateRequest(\n        weight: '12',\n        weightUnit: Components\\WeightUnitEnum::Lb,\n    ),\n    shippoApiVersion: '2018-02-08'\n\n);\n\nif ($response->userParcelTemplate !== null) {\n    // handle response\n}",
                        },
                        {
                            "label": "Java",
                            "lang": "java",
                            "source": 'package hello.world;\n\nimport com.goshippo.shippo_sdk.Shippo;\nimport com.goshippo.shippo_sdk.models.components.UserParcelTemplateCreateRequest;\nimport com.goshippo.shippo_sdk.models.components.UserParcelTemplateWithCarrierTemplateCreateRequest;\nimport com.goshippo.shippo_sdk.models.components.WeightUnitEnum;\nimport com.goshippo.shippo_sdk.models.operations.CreateUserParcelTemplateResponse;\nimport java.lang.Exception;\n\npublic class Application {\n\n    public static void main(String[] args) throws Exception {\n\n        Shippo sdk = Shippo.builder()\n                .apiKeyHeader("ShippoToken <API_TOKEN>")\n                .shippoApiVersion("2018-02-08")\n            .build();\n\n        CreateUserParcelTemplateResponse res = sdk.userParcelTemplates().create()\n                .shippoApiVersion("2018-02-08")\n                .userParcelTemplateCreateRequest(UserParcelTemplateCreateRequest.of(UserParcelTemplateWithCarrierTemplateCreateRequest.builder()\n                    .weight("12")\n                    .weightUnit(WeightUnitEnum.LB)\n                    .build()))\n                .call();\n\n        if (res.userParcelTemplate().isPresent()) {\n            // handle response\n        }\n    }\n}',
                        },
                    ]
                },
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(components.UserParcelTemplate, http_res)
        if utils.match_response(http_res, ["400", "4XX"], "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.SDKError("API error occurred", http_res, http_res_text)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.SDKError("API error occurred", http_res, http_res_text)

        raise errors.SDKError("Unexpected response received", http_res)

    async def create_async(
        self,
        *,
        request: Union[
            components.UserParcelTemplateCreateRequest,
            components.UserParcelTemplateCreateRequestTypedDict,
        ],
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> components.UserParcelTemplate:
        r"""Create a new user parcel template

        Creates a new user parcel template.

        You can choose to create a
        parcel template using a preset carrier template as a starting point, or
        you can create an entirely custom one. To use a preset carrier template,
        pass in a unique template token from [this list](/shippoapi/public-api/parcel-templates)
        plus the weight fields (**weight** and **weight_unit**). Otherwise, omit
        the template field and pass the other fields, for the weight, length, height,
        and depth, as well as their units.\"

        :param request: The request object to send.
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        if not isinstance(request, BaseModel):
            request = utils.unmarshal(
                request, components.UserParcelTemplateCreateRequest
            )
        request = cast(components.UserParcelTemplateCreateRequest, request)

        req = self._build_request_async(
            method="POST",
            path="/user-parcel-templates",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            _globals=operations.CreateUserParcelTemplateGlobals(
                shippo_api_version=self.sdk_configuration.globals.shippo_api_version,
            ),
            security=self.sdk_configuration.security,
            get_serialized_body=lambda: utils.serialize_request_body(
                request,
                False,
                False,
                "json",
                components.UserParcelTemplateCreateRequest,
            ),
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="CreateUserParcelTemplate",
                oauth2_scopes=None,
                security_source=self.sdk_configuration.security,
                tags=["User Parcel Templates"],
                extensions={
                    "x-codeSamples": [
                        {
                            "label": "cURL",
                            "lang": "cURL",
                            "source": 'curl -X POST https://api.goshippo.com/user-parcel-templates  \\\n  -H "Authorization: ShippoToken <API_TOKEN>" \\\n  -H "Content-Type: application/json"\n  -d \'{\n      "name": "My Custom Template",\n      "length": "10",\n      "width": "8",\n      "height": "6",\n      "distance_unit": "in",\n      "weight": "12",\n      "weight_unit": "lb"\n  }\'',
                        },
                        {
                            "label": "Python",
                            "lang": "python",
                            "source": "import shippo\nfrom shippo.models import components\n\ns = shippo.Shippo(\n    api_key_header='ShippoToken <API_TOKEN>',\n    shippo_api_version='2018-02-08',\n)\n\n\nres = s.user_parcel_templates.create(request=components.UserParcelTemplateWithCarrierTemplateCreateRequest(\n    weight='12',\n    weight_unit=components.WeightUnitEnum.LB,\n))\n\nif res is not None:\n    # handle response\n    pass",
                        },
                        {
                            "label": "Typescript",
                            "lang": "typescript",
                            "source": 'import { Shippo } from "shippo";\n\nconst shippo = new Shippo({\n  apiKeyHeader: "ShippoToken <API_TOKEN>",\n  shippoApiVersion: "2018-02-08",\n});\n\nasync function run() {\n  const result = await shippo.userParcelTemplates.create({\n    weight: "12",\n    weightUnit: "lb",\n  });\n\n  // Handle the result\n  console.log(result);\n}\n\nrun();',
                        },
                        {
                            "label": "C#",
                            "lang": "csharp",
                            "source": 'using Shippo;\nusing Shippo.Models.Components;\n\nvar sdk = new ShippoSDK(\n    apiKeyHeader: "ShippoToken <API_TOKEN>",\n    shippoApiVersion: "2018-02-08"\n);\n\nvar res = await sdk.UserParcelTemplates.CreateAsync(\n    userParcelTemplateCreateRequest: UserParcelTemplateCreateRequest.CreateUserParcelTemplateWithCarrierTemplateCreateRequest(\n        new UserParcelTemplateWithCarrierTemplateCreateRequest() {\n            Weight = "12",\n            WeightUnit = WeightUnitEnum.Lb,\n        }\n    ),\n    shippoApiVersion: "2018-02-08"\n);\n\n// handle response',
                        },
                        {
                            "label": "PHP",
                            "lang": "php",
                            "source": "declare(strict_types=1);\n\nrequire 'vendor/autoload.php';\n\nuse Shippo\\API;\nuse Shippo\\API\\Models\\Components;\n\n$sdk = API\\Shippo::builder()\n    ->setSecurity(\n        'ShippoToken <API_TOKEN>'\n    )\n    ->setShippoApiVersion('2018-02-08')\n    ->build();\n\n\n\n$response = $sdk->userParcelTemplates->create(\n    userParcelTemplateCreateRequest: new Components\\UserParcelTemplateWithCarrierTemplateCreateRequest(\n        weight: '12',\n        weightUnit: Components\\WeightUnitEnum::Lb,\n    ),\n    shippoApiVersion: '2018-02-08'\n\n);\n\nif ($response->userParcelTemplate !== null) {\n    // handle response\n}",
                        },
                        {
                            "label": "Java",
                            "lang": "java",
                            "source": 'package hello.world;\n\nimport com.goshippo.shippo_sdk.Shippo;\nimport com.goshippo.shippo_sdk.models.components.UserParcelTemplateCreateRequest;\nimport com.goshippo.shippo_sdk.models.components.UserParcelTemplateWithCarrierTemplateCreateRequest;\nimport com.goshippo.shippo_sdk.models.components.WeightUnitEnum;\nimport com.goshippo.shippo_sdk.models.operations.CreateUserParcelTemplateResponse;\nimport java.lang.Exception;\n\npublic class Application {\n\n    public static void main(String[] args) throws Exception {\n\n        Shippo sdk = Shippo.builder()\n                .apiKeyHeader("ShippoToken <API_TOKEN>")\n                .shippoApiVersion("2018-02-08")\n            .build();\n\n        CreateUserParcelTemplateResponse res = sdk.userParcelTemplates().create()\n                .shippoApiVersion("2018-02-08")\n                .userParcelTemplateCreateRequest(UserParcelTemplateCreateRequest.of(UserParcelTemplateWithCarrierTemplateCreateRequest.builder()\n                    .weight("12")\n                    .weightUnit(WeightUnitEnum.LB)\n                    .build()))\n                .call();\n\n        if (res.userParcelTemplate().isPresent()) {\n            // handle response\n        }\n    }\n}',
                        },
                    ]
                },
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(components.UserParcelTemplate, http_res)
        if utils.match_response(http_res, ["400", "4XX"], "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.SDKError("API error occurred", http_res, http_res_text)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.SDKError("API error occurred", http_res, http_res_text)

        raise errors.SDKError("Unexpected response received", http_res)

    def delete(
        self,
        *,
        user_parcel_template_object_id: str,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ):
        r"""Delete a user parcel template

        Deletes a user parcel template using an object ID.

        :param user_parcel_template_object_id: Object ID of the user parcel template
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = operations.DeleteUserParcelTemplateRequest(
            user_parcel_template_object_id=user_parcel_template_object_id,
        )

        req = self._build_request(
            method="DELETE",
            path="/user-parcel-templates/{UserParcelTemplateObjectId}",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="*/*",
            http_headers=http_headers,
            _globals=operations.DeleteUserParcelTemplateGlobals(
                shippo_api_version=self.sdk_configuration.globals.shippo_api_version,
            ),
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="DeleteUserParcelTemplate",
                oauth2_scopes=None,
                security_source=self.sdk_configuration.security,
                tags=["User Parcel Templates"],
                extensions={
                    "x-codeSamples": [
                        {
                            "label": "cURL",
                            "lang": "cURL",
                            "source": 'curl -X DELETE https://api.goshippo.com/user-parcel-templates/{UserParcelTemplateObjectId}  \\\n  -H "Authorization: ShippoToken <API_TOKEN>"',
                        },
                        {
                            "label": "Python",
                            "lang": "python",
                            "source": "import shippo\n\ns = shippo.Shippo(\n    api_key_header='ShippoToken <API_TOKEN>',\n    shippo_api_version='2018-02-08',\n)\n\n\ns.user_parcel_templates.delete(user_parcel_template_object_id='<id>')\n\n# Use the SDK ...",
                        },
                        {
                            "label": "Typescript",
                            "lang": "typescript",
                            "source": 'import { Shippo } from "shippo";\n\nconst shippo = new Shippo({\n  apiKeyHeader: "ShippoToken <API_TOKEN>",\n  shippoApiVersion: "2018-02-08",\n});\n\nasync function run() {\n  await shippo.userParcelTemplates.delete("<id>");\n\n\n}\n\nrun();',
                        },
                        {
                            "label": "C#",
                            "lang": "csharp",
                            "source": 'using Shippo;\nusing Shippo.Models.Components;\n\nvar sdk = new ShippoSDK(\n    apiKeyHeader: "ShippoToken <API_TOKEN>",\n    shippoApiVersion: "2018-02-08"\n);\n\nawait sdk.UserParcelTemplates.DeleteAsync(\n    userParcelTemplateObjectId: "<id>",\n    shippoApiVersion: "2018-02-08"\n);\n\n// handle response',
                        },
                        {
                            "label": "PHP",
                            "lang": "php",
                            "source": "declare(strict_types=1);\n\nrequire 'vendor/autoload.php';\n\nuse Shippo\\API;\n\n$sdk = API\\Shippo::builder()\n    ->setSecurity(\n        'ShippoToken <API_TOKEN>'\n    )\n    ->setShippoApiVersion('2018-02-08')\n    ->build();\n\n\n\n$response = $sdk->userParcelTemplates->delete(\n    userParcelTemplateObjectId: '<id>',\n    shippoApiVersion: '2018-02-08'\n\n);\n\nif ($response->statusCode === 200) {\n    // handle response\n}",
                        },
                        {
                            "label": "Java",
                            "lang": "java",
                            "source": 'package hello.world;\n\nimport com.goshippo.shippo_sdk.Shippo;\nimport com.goshippo.shippo_sdk.models.operations.DeleteUserParcelTemplateResponse;\nimport java.lang.Exception;\n\npublic class Application {\n\n    public static void main(String[] args) throws Exception {\n\n        Shippo sdk = Shippo.builder()\n                .apiKeyHeader("ShippoToken <API_TOKEN>")\n                .shippoApiVersion("2018-02-08")\n            .build();\n\n        DeleteUserParcelTemplateResponse res = sdk.userParcelTemplates().delete()\n                .userParcelTemplateObjectId("<id>")\n                .shippoApiVersion("2018-02-08")\n                .call();\n\n        // handle response\n    }\n}',
                        },
                    ]
                },
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "204", "*"):
            return
        if utils.match_response(http_res, ["400", "4XX"], "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.SDKError("API error occurred", http_res, http_res_text)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.SDKError("API error occurred", http_res, http_res_text)

        raise errors.SDKError("Unexpected response received", http_res)

    async def delete_async(
        self,
        *,
        user_parcel_template_object_id: str,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ):
        r"""Delete a user parcel template

        Deletes a user parcel template using an object ID.

        :param user_parcel_template_object_id: Object ID of the user parcel template
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = operations.DeleteUserParcelTemplateRequest(
            user_parcel_template_object_id=user_parcel_template_object_id,
        )

        req = self._build_request_async(
            method="DELETE",
            path="/user-parcel-templates/{UserParcelTemplateObjectId}",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="*/*",
            http_headers=http_headers,
            _globals=operations.DeleteUserParcelTemplateGlobals(
                shippo_api_version=self.sdk_configuration.globals.shippo_api_version,
            ),
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="DeleteUserParcelTemplate",
                oauth2_scopes=None,
                security_source=self.sdk_configuration.security,
                tags=["User Parcel Templates"],
                extensions={
                    "x-codeSamples": [
                        {
                            "label": "cURL",
                            "lang": "cURL",
                            "source": 'curl -X DELETE https://api.goshippo.com/user-parcel-templates/{UserParcelTemplateObjectId}  \\\n  -H "Authorization: ShippoToken <API_TOKEN>"',
                        },
                        {
                            "label": "Python",
                            "lang": "python",
                            "source": "import shippo\n\ns = shippo.Shippo(\n    api_key_header='ShippoToken <API_TOKEN>',\n    shippo_api_version='2018-02-08',\n)\n\n\ns.user_parcel_templates.delete(user_parcel_template_object_id='<id>')\n\n# Use the SDK ...",
                        },
                        {
                            "label": "Typescript",
                            "lang": "typescript",
                            "source": 'import { Shippo } from "shippo";\n\nconst shippo = new Shippo({\n  apiKeyHeader: "ShippoToken <API_TOKEN>",\n  shippoApiVersion: "2018-02-08",\n});\n\nasync function run() {\n  await shippo.userParcelTemplates.delete("<id>");\n\n\n}\n\nrun();',
                        },
                        {
                            "label": "C#",
                            "lang": "csharp",
                            "source": 'using Shippo;\nusing Shippo.Models.Components;\n\nvar sdk = new ShippoSDK(\n    apiKeyHeader: "ShippoToken <API_TOKEN>",\n    shippoApiVersion: "2018-02-08"\n);\n\nawait sdk.UserParcelTemplates.DeleteAsync(\n    userParcelTemplateObjectId: "<id>",\n    shippoApiVersion: "2018-02-08"\n);\n\n// handle response',
                        },
                        {
                            "label": "PHP",
                            "lang": "php",
                            "source": "declare(strict_types=1);\n\nrequire 'vendor/autoload.php';\n\nuse Shippo\\API;\n\n$sdk = API\\Shippo::builder()\n    ->setSecurity(\n        'ShippoToken <API_TOKEN>'\n    )\n    ->setShippoApiVersion('2018-02-08')\n    ->build();\n\n\n\n$response = $sdk->userParcelTemplates->delete(\n    userParcelTemplateObjectId: '<id>',\n    shippoApiVersion: '2018-02-08'\n\n);\n\nif ($response->statusCode === 200) {\n    // handle response\n}",
                        },
                        {
                            "label": "Java",
                            "lang": "java",
                            "source": 'package hello.world;\n\nimport com.goshippo.shippo_sdk.Shippo;\nimport com.goshippo.shippo_sdk.models.operations.DeleteUserParcelTemplateResponse;\nimport java.lang.Exception;\n\npublic class Application {\n\n    public static void main(String[] args) throws Exception {\n\n        Shippo sdk = Shippo.builder()\n                .apiKeyHeader("ShippoToken <API_TOKEN>")\n                .shippoApiVersion("2018-02-08")\n            .build();\n\n        DeleteUserParcelTemplateResponse res = sdk.userParcelTemplates().delete()\n                .userParcelTemplateObjectId("<id>")\n                .shippoApiVersion("2018-02-08")\n                .call();\n\n        // handle response\n    }\n}',
                        },
                    ]
                },
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "204", "*"):
            return
        if utils.match_response(http_res, ["400", "4XX"], "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.SDKError("API error occurred", http_res, http_res_text)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.SDKError("API error occurred", http_res, http_res_text)

        raise errors.SDKError("Unexpected response received", http_res)

    def get(
        self,
        *,
        user_parcel_template_object_id: str,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> components.UserParcelTemplate:
        r"""Retrieves a user parcel template

        Returns the parcel template information for a specific user parcel
        template, identified by the object ID.

        :param user_parcel_template_object_id: Object ID of the user parcel template
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = operations.GetUserParcelTemplateRequest(
            user_parcel_template_object_id=user_parcel_template_object_id,
        )

        req = self._build_request(
            method="GET",
            path="/user-parcel-templates/{UserParcelTemplateObjectId}",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            _globals=operations.GetUserParcelTemplateGlobals(
                shippo_api_version=self.sdk_configuration.globals.shippo_api_version,
            ),
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="GetUserParcelTemplate",
                oauth2_scopes=None,
                security_source=self.sdk_configuration.security,
                tags=["User Parcel Templates"],
                extensions={
                    "x-codeSamples": [
                        {
                            "label": "CLI",
                            "lang": "cURL",
                            "source": 'curl /user-parcel-templates/{UserParcelTemplateToken}  \\\n  -H "Authorization: ShippoToken <API_TOKEN>" \\\n  -H "Content-Type: application/json"',
                        },
                        {
                            "label": "Python",
                            "lang": "python",
                            "source": "import shippo\n\ns = shippo.Shippo(\n    api_key_header='ShippoToken <API_TOKEN>',\n    shippo_api_version='2018-02-08',\n)\n\n\nres = s.user_parcel_templates.get(user_parcel_template_object_id='<id>')\n\nif res is not None:\n    # handle response\n    pass",
                        },
                        {
                            "label": "Typescript",
                            "lang": "typescript",
                            "source": 'import { Shippo } from "shippo";\n\nconst shippo = new Shippo({\n  apiKeyHeader: "ShippoToken <API_TOKEN>",\n  shippoApiVersion: "2018-02-08",\n});\n\nasync function run() {\n  const result = await shippo.userParcelTemplates.get("<id>");\n\n  // Handle the result\n  console.log(result);\n}\n\nrun();',
                        },
                        {
                            "label": "C#",
                            "lang": "csharp",
                            "source": 'using Shippo;\nusing Shippo.Models.Components;\n\nvar sdk = new ShippoSDK(\n    apiKeyHeader: "ShippoToken <API_TOKEN>",\n    shippoApiVersion: "2018-02-08"\n);\n\nvar res = await sdk.UserParcelTemplates.GetAsync(\n    userParcelTemplateObjectId: "<id>",\n    shippoApiVersion: "2018-02-08"\n);\n\n// handle response',
                        },
                        {
                            "label": "PHP",
                            "lang": "php",
                            "source": "declare(strict_types=1);\n\nrequire 'vendor/autoload.php';\n\nuse Shippo\\API;\n\n$sdk = API\\Shippo::builder()\n    ->setSecurity(\n        'ShippoToken <API_TOKEN>'\n    )\n    ->setShippoApiVersion('2018-02-08')\n    ->build();\n\n\n\n$response = $sdk->userParcelTemplates->get(\n    userParcelTemplateObjectId: '<id>',\n    shippoApiVersion: '2018-02-08'\n\n);\n\nif ($response->userParcelTemplate !== null) {\n    // handle response\n}",
                        },
                        {
                            "label": "Java",
                            "lang": "java",
                            "source": 'package hello.world;\n\nimport com.goshippo.shippo_sdk.Shippo;\nimport com.goshippo.shippo_sdk.models.operations.GetUserParcelTemplateResponse;\nimport java.lang.Exception;\n\npublic class Application {\n\n    public static void main(String[] args) throws Exception {\n\n        Shippo sdk = Shippo.builder()\n                .apiKeyHeader("ShippoToken <API_TOKEN>")\n                .shippoApiVersion("2018-02-08")\n            .build();\n\n        GetUserParcelTemplateResponse res = sdk.userParcelTemplates().get()\n                .userParcelTemplateObjectId("<id>")\n                .shippoApiVersion("2018-02-08")\n                .call();\n\n        if (res.userParcelTemplate().isPresent()) {\n            // handle response\n        }\n    }\n}',
                        },
                    ]
                },
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(components.UserParcelTemplate, http_res)
        if utils.match_response(http_res, ["400", "4XX"], "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.SDKError("API error occurred", http_res, http_res_text)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.SDKError("API error occurred", http_res, http_res_text)

        raise errors.SDKError("Unexpected response received", http_res)

    async def get_async(
        self,
        *,
        user_parcel_template_object_id: str,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> components.UserParcelTemplate:
        r"""Retrieves a user parcel template

        Returns the parcel template information for a specific user parcel
        template, identified by the object ID.

        :param user_parcel_template_object_id: Object ID of the user parcel template
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = operations.GetUserParcelTemplateRequest(
            user_parcel_template_object_id=user_parcel_template_object_id,
        )

        req = self._build_request_async(
            method="GET",
            path="/user-parcel-templates/{UserParcelTemplateObjectId}",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            _globals=operations.GetUserParcelTemplateGlobals(
                shippo_api_version=self.sdk_configuration.globals.shippo_api_version,
            ),
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="GetUserParcelTemplate",
                oauth2_scopes=None,
                security_source=self.sdk_configuration.security,
                tags=["User Parcel Templates"],
                extensions={
                    "x-codeSamples": [
                        {
                            "label": "CLI",
                            "lang": "cURL",
                            "source": 'curl /user-parcel-templates/{UserParcelTemplateToken}  \\\n  -H "Authorization: ShippoToken <API_TOKEN>" \\\n  -H "Content-Type: application/json"',
                        },
                        {
                            "label": "Python",
                            "lang": "python",
                            "source": "import shippo\n\ns = shippo.Shippo(\n    api_key_header='ShippoToken <API_TOKEN>',\n    shippo_api_version='2018-02-08',\n)\n\n\nres = s.user_parcel_templates.get(user_parcel_template_object_id='<id>')\n\nif res is not None:\n    # handle response\n    pass",
                        },
                        {
                            "label": "Typescript",
                            "lang": "typescript",
                            "source": 'import { Shippo } from "shippo";\n\nconst shippo = new Shippo({\n  apiKeyHeader: "ShippoToken <API_TOKEN>",\n  shippoApiVersion: "2018-02-08",\n});\n\nasync function run() {\n  const result = await shippo.userParcelTemplates.get("<id>");\n\n  // Handle the result\n  console.log(result);\n}\n\nrun();',
                        },
                        {
                            "label": "C#",
                            "lang": "csharp",
                            "source": 'using Shippo;\nusing Shippo.Models.Components;\n\nvar sdk = new ShippoSDK(\n    apiKeyHeader: "ShippoToken <API_TOKEN>",\n    shippoApiVersion: "2018-02-08"\n);\n\nvar res = await sdk.UserParcelTemplates.GetAsync(\n    userParcelTemplateObjectId: "<id>",\n    shippoApiVersion: "2018-02-08"\n);\n\n// handle response',
                        },
                        {
                            "label": "PHP",
                            "lang": "php",
                            "source": "declare(strict_types=1);\n\nrequire 'vendor/autoload.php';\n\nuse Shippo\\API;\n\n$sdk = API\\Shippo::builder()\n    ->setSecurity(\n        'ShippoToken <API_TOKEN>'\n    )\n    ->setShippoApiVersion('2018-02-08')\n    ->build();\n\n\n\n$response = $sdk->userParcelTemplates->get(\n    userParcelTemplateObjectId: '<id>',\n    shippoApiVersion: '2018-02-08'\n\n);\n\nif ($response->userParcelTemplate !== null) {\n    // handle response\n}",
                        },
                        {
                            "label": "Java",
                            "lang": "java",
                            "source": 'package hello.world;\n\nimport com.goshippo.shippo_sdk.Shippo;\nimport com.goshippo.shippo_sdk.models.operations.GetUserParcelTemplateResponse;\nimport java.lang.Exception;\n\npublic class Application {\n\n    public static void main(String[] args) throws Exception {\n\n        Shippo sdk = Shippo.builder()\n                .apiKeyHeader("ShippoToken <API_TOKEN>")\n                .shippoApiVersion("2018-02-08")\n            .build();\n\n        GetUserParcelTemplateResponse res = sdk.userParcelTemplates().get()\n                .userParcelTemplateObjectId("<id>")\n                .shippoApiVersion("2018-02-08")\n                .call();\n\n        if (res.userParcelTemplate().isPresent()) {\n            // handle response\n        }\n    }\n}',
                        },
                    ]
                },
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(components.UserParcelTemplate, http_res)
        if utils.match_response(http_res, ["400", "4XX"], "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.SDKError("API error occurred", http_res, http_res_text)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.SDKError("API error occurred", http_res, http_res_text)

        raise errors.SDKError("Unexpected response received", http_res)

    def update(
        self,
        *,
        user_parcel_template_object_id: str,
        user_parcel_template_update_request: Optional[
            Union[
                components.UserParcelTemplateUpdateRequest,
                components.UserParcelTemplateUpdateRequestTypedDict,
            ]
        ] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> components.UserParcelTemplate:
        r"""Update an existing user parcel template

        Updates an existing user parcel template.

        :param user_parcel_template_object_id: Object ID of the user parcel template
        :param user_parcel_template_update_request:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = operations.UpdateUserParcelTemplateRequest(
            user_parcel_template_object_id=user_parcel_template_object_id,
            user_parcel_template_update_request=utils.get_pydantic_model(
                user_parcel_template_update_request,
                Optional[components.UserParcelTemplateUpdateRequest],
            ),
        )

        req = self._build_request(
            method="PUT",
            path="/user-parcel-templates/{UserParcelTemplateObjectId}",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            _globals=operations.UpdateUserParcelTemplateGlobals(
                shippo_api_version=self.sdk_configuration.globals.shippo_api_version,
            ),
            security=self.sdk_configuration.security,
            get_serialized_body=lambda: utils.serialize_request_body(
                request.user_parcel_template_update_request
                if request is not None
                else None,
                False,
                True,
                "json",
                Optional[components.UserParcelTemplateUpdateRequest],
            ),
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="UpdateUserParcelTemplate",
                oauth2_scopes=None,
                security_source=self.sdk_configuration.security,
                tags=["User Parcel Templates"],
                extensions={
                    "x-codeSamples": [
                        {
                            "label": "cURL",
                            "lang": "cURL",
                            "source": 'curl https://api.goshippo.com/user-parcel-templates/b958d3690bb04bb8b2986724872750f5  \\\n-H "Authorization: ShippoToken <API_TOKEN>" \\\n-H "Content-Type: application/json"\n  -d \'{\n      "name": "My Custom Template",\n      "length": "10",\n      "width": "8",\n      "height": "6",\n      "distance_unit": "in",\n      "weight": "12",\n      "weight_unit": "lb"\n  }\'',
                        },
                        {
                            "label": "Python",
                            "lang": "python",
                            "source": "import shippo\nfrom shippo.models import components\n\ns = shippo.Shippo(\n    api_key_header='ShippoToken <API_TOKEN>',\n    shippo_api_version='2018-02-08',\n)\n\n\nres = s.user_parcel_templates.update(user_parcel_template_object_id='<id>', user_parcel_template_update_request=components.UserParcelTemplateUpdateRequest(\n    distance_unit=components.DistanceUnitEnum.IN,\n    height='6',\n    length='10',\n    name='My Custom Template',\n    weight='12',\n    weight_unit=components.WeightUnitEnum.LB,\n    width='8',\n))\n\nif res is not None:\n    # handle response\n    pass",
                        },
                        {
                            "label": "Typescript",
                            "lang": "typescript",
                            "source": 'import { Shippo } from "shippo";\n\nconst shippo = new Shippo({\n  apiKeyHeader: "ShippoToken <API_TOKEN>",\n  shippoApiVersion: "2018-02-08",\n});\n\nasync function run() {\n  const result = await shippo.userParcelTemplates.update("<id>", {\n    distanceUnit: "in",\n    height: "6",\n    length: "10",\n    name: "My Custom Template",\n    weight: "12",\n    weightUnit: "lb",\n    width: "8",\n  });\n\n  // Handle the result\n  console.log(result);\n}\n\nrun();',
                        },
                        {
                            "label": "C#",
                            "lang": "csharp",
                            "source": 'using Shippo;\nusing Shippo.Models.Components;\n\nvar sdk = new ShippoSDK(\n    apiKeyHeader: "ShippoToken <API_TOKEN>",\n    shippoApiVersion: "2018-02-08"\n);\n\nvar res = await sdk.UserParcelTemplates.UpdateAsync(\n    userParcelTemplateObjectId: "<id>",\n    shippoApiVersion: "2018-02-08",\n    userParcelTemplateUpdateRequest: new UserParcelTemplateUpdateRequest() {\n        DistanceUnit = DistanceUnitEnum.In,\n        Height = "6",\n        Length = "10",\n        Name = "My Custom Template",\n        Weight = "12",\n        WeightUnit = WeightUnitEnum.Lb,\n        Width = "8",\n    }\n);\n\n// handle response',
                        },
                        {
                            "label": "PHP",
                            "lang": "php",
                            "source": "declare(strict_types=1);\n\nrequire 'vendor/autoload.php';\n\nuse Shippo\\API;\nuse Shippo\\API\\Models\\Components;\n\n$sdk = API\\Shippo::builder()\n    ->setSecurity(\n        'ShippoToken <API_TOKEN>'\n    )\n    ->setShippoApiVersion('2018-02-08')\n    ->build();\n\n$userParcelTemplateUpdateRequest = new Components\\UserParcelTemplateUpdateRequest(\n    distanceUnit: Components\\DistanceUnitEnum::In,\n    height: '6',\n    length: '10',\n    name: 'My Custom Template',\n    weight: '12',\n    weightUnit: Components\\WeightUnitEnum::Lb,\n    width: '8',\n);\n\n$response = $sdk->userParcelTemplates->update(\n    userParcelTemplateObjectId: '<id>',\n    shippoApiVersion: '2018-02-08',\n    userParcelTemplateUpdateRequest: $userParcelTemplateUpdateRequest\n\n);\n\nif ($response->userParcelTemplate !== null) {\n    // handle response\n}",
                        },
                        {
                            "label": "Java",
                            "lang": "java",
                            "source": 'package hello.world;\n\nimport com.goshippo.shippo_sdk.Shippo;\nimport com.goshippo.shippo_sdk.models.components.DistanceUnitEnum;\nimport com.goshippo.shippo_sdk.models.components.UserParcelTemplateUpdateRequest;\nimport com.goshippo.shippo_sdk.models.components.WeightUnitEnum;\nimport com.goshippo.shippo_sdk.models.operations.UpdateUserParcelTemplateResponse;\nimport java.lang.Exception;\n\npublic class Application {\n\n    public static void main(String[] args) throws Exception {\n\n        Shippo sdk = Shippo.builder()\n                .apiKeyHeader("ShippoToken <API_TOKEN>")\n                .shippoApiVersion("2018-02-08")\n            .build();\n\n        UpdateUserParcelTemplateResponse res = sdk.userParcelTemplates().update()\n                .userParcelTemplateObjectId("<id>")\n                .shippoApiVersion("2018-02-08")\n                .userParcelTemplateUpdateRequest(UserParcelTemplateUpdateRequest.builder()\n                    .distanceUnit(DistanceUnitEnum.IN)\n                    .height("6")\n                    .length("10")\n                    .name("My Custom Template")\n                    .width("8")\n                    .weight("12")\n                    .weightUnit(WeightUnitEnum.LB)\n                    .build())\n                .call();\n\n        if (res.userParcelTemplate().isPresent()) {\n            // handle response\n        }\n    }\n}',
                        },
                    ]
                },
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(components.UserParcelTemplate, http_res)
        if utils.match_response(http_res, ["400", "4XX"], "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.SDKError("API error occurred", http_res, http_res_text)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.SDKError("API error occurred", http_res, http_res_text)

        raise errors.SDKError("Unexpected response received", http_res)

    async def update_async(
        self,
        *,
        user_parcel_template_object_id: str,
        user_parcel_template_update_request: Optional[
            Union[
                components.UserParcelTemplateUpdateRequest,
                components.UserParcelTemplateUpdateRequestTypedDict,
            ]
        ] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> components.UserParcelTemplate:
        r"""Update an existing user parcel template

        Updates an existing user parcel template.

        :param user_parcel_template_object_id: Object ID of the user parcel template
        :param user_parcel_template_update_request:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = operations.UpdateUserParcelTemplateRequest(
            user_parcel_template_object_id=user_parcel_template_object_id,
            user_parcel_template_update_request=utils.get_pydantic_model(
                user_parcel_template_update_request,
                Optional[components.UserParcelTemplateUpdateRequest],
            ),
        )

        req = self._build_request_async(
            method="PUT",
            path="/user-parcel-templates/{UserParcelTemplateObjectId}",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            _globals=operations.UpdateUserParcelTemplateGlobals(
                shippo_api_version=self.sdk_configuration.globals.shippo_api_version,
            ),
            security=self.sdk_configuration.security,
            get_serialized_body=lambda: utils.serialize_request_body(
                request.user_parcel_template_update_request
                if request is not None
                else None,
                False,
                True,
                "json",
                Optional[components.UserParcelTemplateUpdateRequest],
            ),
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="UpdateUserParcelTemplate",
                oauth2_scopes=None,
                security_source=self.sdk_configuration.security,
                tags=["User Parcel Templates"],
                extensions={
                    "x-codeSamples": [
                        {
                            "label": "cURL",
                            "lang": "cURL",
                            "source": 'curl https://api.goshippo.com/user-parcel-templates/b958d3690bb04bb8b2986724872750f5  \\\n-H "Authorization: ShippoToken <API_TOKEN>" \\\n-H "Content-Type: application/json"\n  -d \'{\n      "name": "My Custom Template",\n      "length": "10",\n      "width": "8",\n      "height": "6",\n      "distance_unit": "in",\n      "weight": "12",\n      "weight_unit": "lb"\n  }\'',
                        },
                        {
                            "label": "Python",
                            "lang": "python",
                            "source": "import shippo\nfrom shippo.models import components\n\ns = shippo.Shippo(\n    api_key_header='ShippoToken <API_TOKEN>',\n    shippo_api_version='2018-02-08',\n)\n\n\nres = s.user_parcel_templates.update(user_parcel_template_object_id='<id>', user_parcel_template_update_request=components.UserParcelTemplateUpdateRequest(\n    distance_unit=components.DistanceUnitEnum.IN,\n    height='6',\n    length='10',\n    name='My Custom Template',\n    weight='12',\n    weight_unit=components.WeightUnitEnum.LB,\n    width='8',\n))\n\nif res is not None:\n    # handle response\n    pass",
                        },
                        {
                            "label": "Typescript",
                            "lang": "typescript",
                            "source": 'import { Shippo } from "shippo";\n\nconst shippo = new Shippo({\n  apiKeyHeader: "ShippoToken <API_TOKEN>",\n  shippoApiVersion: "2018-02-08",\n});\n\nasync function run() {\n  const result = await shippo.userParcelTemplates.update("<id>", {\n    distanceUnit: "in",\n    height: "6",\n    length: "10",\n    name: "My Custom Template",\n    weight: "12",\n    weightUnit: "lb",\n    width: "8",\n  });\n\n  // Handle the result\n  console.log(result);\n}\n\nrun();',
                        },
                        {
                            "label": "C#",
                            "lang": "csharp",
                            "source": 'using Shippo;\nusing Shippo.Models.Components;\n\nvar sdk = new ShippoSDK(\n    apiKeyHeader: "ShippoToken <API_TOKEN>",\n    shippoApiVersion: "2018-02-08"\n);\n\nvar res = await sdk.UserParcelTemplates.UpdateAsync(\n    userParcelTemplateObjectId: "<id>",\n    shippoApiVersion: "2018-02-08",\n    userParcelTemplateUpdateRequest: new UserParcelTemplateUpdateRequest() {\n        DistanceUnit = DistanceUnitEnum.In,\n        Height = "6",\n        Length = "10",\n        Name = "My Custom Template",\n        Weight = "12",\n        WeightUnit = WeightUnitEnum.Lb,\n        Width = "8",\n    }\n);\n\n// handle response',
                        },
                        {
                            "label": "PHP",
                            "lang": "php",
                            "source": "declare(strict_types=1);\n\nrequire 'vendor/autoload.php';\n\nuse Shippo\\API;\nuse Shippo\\API\\Models\\Components;\n\n$sdk = API\\Shippo::builder()\n    ->setSecurity(\n        'ShippoToken <API_TOKEN>'\n    )\n    ->setShippoApiVersion('2018-02-08')\n    ->build();\n\n$userParcelTemplateUpdateRequest = new Components\\UserParcelTemplateUpdateRequest(\n    distanceUnit: Components\\DistanceUnitEnum::In,\n    height: '6',\n    length: '10',\n    name: 'My Custom Template',\n    weight: '12',\n    weightUnit: Components\\WeightUnitEnum::Lb,\n    width: '8',\n);\n\n$response = $sdk->userParcelTemplates->update(\n    userParcelTemplateObjectId: '<id>',\n    shippoApiVersion: '2018-02-08',\n    userParcelTemplateUpdateRequest: $userParcelTemplateUpdateRequest\n\n);\n\nif ($response->userParcelTemplate !== null) {\n    // handle response\n}",
                        },
                        {
                            "label": "Java",
                            "lang": "java",
                            "source": 'package hello.world;\n\nimport com.goshippo.shippo_sdk.Shippo;\nimport com.goshippo.shippo_sdk.models.components.DistanceUnitEnum;\nimport com.goshippo.shippo_sdk.models.components.UserParcelTemplateUpdateRequest;\nimport com.goshippo.shippo_sdk.models.components.WeightUnitEnum;\nimport com.goshippo.shippo_sdk.models.operations.UpdateUserParcelTemplateResponse;\nimport java.lang.Exception;\n\npublic class Application {\n\n    public static void main(String[] args) throws Exception {\n\n        Shippo sdk = Shippo.builder()\n                .apiKeyHeader("ShippoToken <API_TOKEN>")\n                .shippoApiVersion("2018-02-08")\n            .build();\n\n        UpdateUserParcelTemplateResponse res = sdk.userParcelTemplates().update()\n                .userParcelTemplateObjectId("<id>")\n                .shippoApiVersion("2018-02-08")\n                .userParcelTemplateUpdateRequest(UserParcelTemplateUpdateRequest.builder()\n                    .distanceUnit(DistanceUnitEnum.IN)\n                    .height("6")\n                    .length("10")\n                    .name("My Custom Template")\n                    .width("8")\n                    .weight("12")\n                    .weightUnit(WeightUnitEnum.LB)\n                    .build())\n                .call();\n\n        if (res.userParcelTemplate().isPresent()) {\n            // handle response\n        }\n    }\n}',
                        },
                    ]
                },
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(components.UserParcelTemplate, http_res)
        if utils.match_response(http_res, ["400", "4XX"], "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.SDKError("API error occurred", http_res, http_res_text)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.SDKError("API error occurred", http_res, http_res_text)

        raise errors.SDKError("Unexpected response received", http_res)
