"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ...models.components import parcelcreatefromtemplaterequest as components_parcelcreatefromtemplaterequest
from ...models.components import parcelcreaterequest as components_parcelcreaterequest
from typing import Optional, Union


@dataclasses.dataclass
class CreateParcelGlobals:
    shippo_api_version: Optional[str] = dataclasses.field(default=None, metadata={'header': { 'field_name': 'SHIPPO-API-VERSION', 'style': 'simple', 'explode': False }})
    r"""String used to pick a non-default API version to use"""
    


CreateParcelRequestBody = Union[components_parcelcreaterequest.ParcelCreateRequest, components_parcelcreatefromtemplaterequest.ParcelCreateFromTemplateRequest]
