"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from enum import Enum
from typing import Optional


@dataclasses.dataclass
class GetCarrierRegistrationStatusGlobals:
    shippo_api_version: Optional[str] = dataclasses.field(default=None, metadata={'header': { 'field_name': 'SHIPPO-API-VERSION', 'style': 'simple', 'explode': False }})
    r"""Optional string used to pick a non-default API version to use. See our <a href=\\"https://docs.goshippo.com/docs/api_concepts/apiversioning/\\">API version</a> guide."""
    



class Carrier(str, Enum):
    r"""filter by specific carrier"""
    UPS = 'ups'
    USPS = 'usps'
    CANADA_POST = 'canada_post'


@dataclasses.dataclass
class GetCarrierRegistrationStatusRequest:
    carrier: Carrier = dataclasses.field(metadata={'query_param': { 'field_name': 'carrier', 'style': 'form', 'explode': True }})
    r"""filter by specific carrier"""
    

