"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from shippo.models.components import trackingstatusenum as components_trackingstatusenum, transactionstatusenum as components_transactionstatusenum
from shippo.types import BaseModel
from shippo.utils import FieldMetadata, HeaderMetadata, QueryParamMetadata
from typing import Optional, TypedDict
from typing_extensions import Annotated, NotRequired


class ListTransactionsGlobalsTypedDict(TypedDict):
    shippo_api_version: NotRequired[str]
    r"""String used to pick a non-default API version to use"""
    

class ListTransactionsGlobals(BaseModel):
    shippo_api_version: Annotated[Optional[str], pydantic.Field(alias="SHIPPO-API-VERSION"), FieldMetadata(header=HeaderMetadata(style="simple", explode=False))] = None
    r"""String used to pick a non-default API version to use"""
    

class ListTransactionsRequestTypedDict(TypedDict):
    rate: NotRequired[str]
    r"""Filter by rate ID"""
    object_status: NotRequired[components_transactionstatusenum.TransactionStatusEnum]
    r"""Filter by object status"""
    tracking_status: NotRequired[components_trackingstatusenum.TrackingStatusEnum]
    r"""Filter by tracking status"""
    page: NotRequired[int]
    r"""The page number you want to select"""
    results: NotRequired[int]
    r"""The number of results to return per page (max 100)"""
    

class ListTransactionsRequest(BaseModel):
    rate: Annotated[Optional[str], FieldMetadata(query=QueryParamMetadata(style="form", explode=True))] = None
    r"""Filter by rate ID"""
    object_status: Annotated[Optional[components_transactionstatusenum.TransactionStatusEnum], FieldMetadata(query=QueryParamMetadata(style="form", explode=True))] = None
    r"""Filter by object status"""
    tracking_status: Annotated[Optional[components_trackingstatusenum.TrackingStatusEnum], FieldMetadata(query=QueryParamMetadata(style="form", explode=True))] = None
    r"""Filter by tracking status"""
    page: Annotated[Optional[int], FieldMetadata(query=QueryParamMetadata(style="form", explode=True))] = 1
    r"""The page number you want to select"""
    results: Annotated[Optional[int], FieldMetadata(query=QueryParamMetadata(style="form", explode=True))] = 25
    r"""The number of results to return per page (max 100)"""
    
