"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from shippo.models.components import webhookupdaterequest as components_webhookupdaterequest
from shippo.types import BaseModel
from shippo.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing import TypedDict
from typing_extensions import Annotated


class UpdateWebhookRequestTypedDict(TypedDict):
    webhook_id: str
    r"""Object ID of the webhook to retrieve"""
    webhook_update_request: components_webhookupdaterequest.WebhookUpdateRequestTypedDict
    

class UpdateWebhookRequest(BaseModel):
    webhook_id: Annotated[str, pydantic.Field(alias="webhookId"), FieldMetadata(path=PathParamMetadata(style="simple", explode=False))]
    r"""Object ID of the webhook to retrieve"""
    webhook_update_request: Annotated[components_webhookupdaterequest.WebhookUpdateRequest, FieldMetadata(request=RequestMetadata(media_type="application/json"))]
    
