"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from .carrieraccountcanadapostcreateparameters import CarrierAccountCanadaPostCreateParameters
from dataclasses_json import Undefined, dataclass_json
from shippo import utils
from typing import Final


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class CarrierAccountCanadaPostCreateRequest:
    parameters: CarrierAccountCanadaPostCreateParameters = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('parameters') }})
    CARRIER: Final[str] = dataclasses.field(default='canada_post', metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('carrier') }})
    

