"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from shippo.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class CarrierAccountRegistrationStatusTypedDict(TypedDict):
    carrier_account: NotRequired[str]
    object_created: NotRequired[datetime]
    object_owner: NotRequired[str]
    object_updated: NotRequired[datetime]
    status: NotRequired[str]


class CarrierAccountRegistrationStatus(BaseModel):
    carrier_account: Optional[str] = None

    object_created: Optional[datetime] = None

    object_owner: Optional[str] = None

    object_updated: Optional[datetime] = None

    status: Optional[str] = None
