"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from pydantic import model_serializer
from shippo.types import BaseModel, UNSET_SENTINEL
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class CarrierAccountRegistrationStatusTypedDict(TypedDict):
    carrier_account: NotRequired[str]
    object_created: NotRequired[datetime]
    object_owner: NotRequired[str]
    object_updated: NotRequired[datetime]
    status: NotRequired[str]


class CarrierAccountRegistrationStatus(BaseModel):
    carrier_account: Optional[str] = None

    object_created: Optional[datetime] = None

    object_owner: Optional[str] = None

    object_updated: Optional[datetime] = None

    status: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "carrier_account",
                "object_created",
                "object_owner",
                "object_updated",
                "status",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
