"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from shippo.types import BaseModel
from typing import TypedDict


class CarrierAccountDeutschePostCreateRequestParametersTypedDict(TypedDict):
    pass
    

class CarrierAccountDeutschePostCreateRequestParameters(BaseModel):
    pass
    

class CarrierAccountDeutschePostCreateRequestTypedDict(TypedDict):
    carrier: str
    parameters: CarrierAccountDeutschePostCreateRequestParametersTypedDict
    

class CarrierAccountDeutschePostCreateRequest(BaseModel):
    carrier: str
    parameters: CarrierAccountDeutschePostCreateRequestParameters
    
