"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic.functional_validators import AfterValidator
from shippo.types import BaseModel
from shippo.utils import validate_const
from typing import Literal
from typing_extensions import Annotated, TypedDict


class CarrierAccountPosteItalianeCreateRequestParametersTypedDict(TypedDict):
    pass


class CarrierAccountPosteItalianeCreateRequestParameters(BaseModel):
    pass


class CarrierAccountPosteItalianeCreateRequestTypedDict(TypedDict):
    parameters: CarrierAccountPosteItalianeCreateRequestParametersTypedDict
    carrier: Literal["poste_italiane"]


class CarrierAccountPosteItalianeCreateRequest(BaseModel):
    parameters: CarrierAccountPosteItalianeCreateRequestParameters

    CARRIER: Annotated[
        Annotated[
            Literal["poste_italiane"], AfterValidator(validate_const("poste_italiane"))
        ],
        pydantic.Field(alias="carrier"),
    ] = "poste_italiane"
