"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from shippo.types import BaseModel
from typing_extensions import TypedDict


class CarrierAccountCanadaPostCreateParametersTypedDict(TypedDict):
    canada_post_terms: bool
    r"""Whether or not the user agrees to Canada Post's terms. If passed in as false, request will fail with error 400"""
    company: str
    email: str
    full_name: str
    phone: str
    r"""Needs to be a valid phone number and cannot be null"""


class CarrierAccountCanadaPostCreateParameters(BaseModel):
    canada_post_terms: bool
    r"""Whether or not the user agrees to Canada Post's terms. If passed in as false, request will fail with error 400"""

    company: str

    email: str

    full_name: str

    phone: str
    r"""Needs to be a valid phone number and cannot be null"""
