"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pydantic import model_serializer
from shippo.types import BaseModel, UNSET_SENTINEL
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class CustomsInvoicedChargesTypedDict(TypedDict):
    r"""Additional invoiced charges to be shown on the Customs Declaration Commercial Invoice."""

    currency: str
    r"""Currency for the invoiced charges amounts incurred on the end consumer."""
    total_shipping: NotRequired[str]
    r"""Total shipping paid by the buyer."""
    total_taxes: NotRequired[str]
    r"""Total taxes paid by the buyer."""
    total_duties: NotRequired[str]
    r"""Total duties paid by the buyer."""
    other_fees: NotRequired[str]
    r"""Other fees paid by the buyer."""


class CustomsInvoicedCharges(BaseModel):
    r"""Additional invoiced charges to be shown on the Customs Declaration Commercial Invoice."""

    currency: str
    r"""Currency for the invoiced charges amounts incurred on the end consumer."""

    total_shipping: Optional[str] = None
    r"""Total shipping paid by the buyer."""

    total_taxes: Optional[str] = None
    r"""Total taxes paid by the buyer."""

    total_duties: Optional[str] = None
    r"""Total duties paid by the buyer."""

    other_fees: Optional[str] = None
    r"""Other fees paid by the buyer."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["total_shipping", "total_taxes", "total_duties", "other_fees"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
