"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .customsitem import CustomsItem, CustomsItemTypedDict
from shippo.types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class CustomsItemPaginatedListTypedDict(TypedDict):
    next: NotRequired[str]
    previous: NotRequired[str]
    results: NotRequired[List[CustomsItemTypedDict]]


class CustomsItemPaginatedList(BaseModel):
    next: Optional[str] = None

    previous: Optional[str] = None

    results: Optional[List[CustomsItem]] = None
