"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from shippo.types import BaseModel
from typing_extensions import TypedDict


class EmbeddedAuthorizationRequestTypedDict(TypedDict):
    scope: str
    r"""The scope requested for the token."""


class EmbeddedAuthorizationRequest(BaseModel):
    scope: str
    r"""The scope requested for the token."""
