"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .liverate import LiveRate, LiveRateTypedDict
from pydantic import model_serializer
from shippo.types import BaseModel, UNSET_SENTINEL
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class LiveRatePaginatedListTypedDict(TypedDict):
    next: NotRequired[str]
    previous: NotRequired[str]
    count: NotRequired[int]
    results: NotRequired[List[LiveRateTypedDict]]


class LiveRatePaginatedList(BaseModel):
    next: Optional[str] = None

    previous: Optional[str] = None

    count: Optional[int] = None

    results: Optional[List[LiveRate]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["next", "previous", "count", "results"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
