"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .rate import Rate, RateTypedDict
from shippo.types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class RatePaginatedListTypedDict(TypedDict):
    next: NotRequired[str]
    previous: NotRequired[str]
    results: NotRequired[List[RateTypedDict]]


class RatePaginatedList(BaseModel):
    next: Optional[str] = None

    previous: Optional[str] = None

    results: Optional[List[Rate]] = None
