"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .refund import Refund, RefundTypedDict
from shippo.types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class RefundPaginatedListTypedDict(TypedDict):
    next: NotRequired[str]
    previous: NotRequired[str]
    results: NotRequired[List[RefundTypedDict]]


class RefundPaginatedList(BaseModel):
    next: Optional[str] = None

    previous: Optional[str] = None

    results: Optional[List[Refund]] = None
