"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .servicelevel import ServiceLevel, ServiceLevelTypedDict
from pydantic import model_serializer
from shippo.types import BaseModel, UNSET_SENTINEL
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class ServiceLevelWithParentTypedDict(TypedDict):
    r"""Contains details regarding the service level for the given rate."""

    name: NotRequired[str]
    r"""Name of the Rate's servicelevel, e.g. `International Priority` or `Standard Post`.
    A servicelevel commonly defines the transit time of a Shipment (e.g., Express vs. Standard), along with other properties.
    These names vary depending on the provider.
    """
    terms: NotRequired[str]
    r"""Further clarification of the service."""
    token: NotRequired[str]
    r"""Token of the Rate's servicelevel, e.g. `usps_priority` or `fedex_ground`.
    See <a href=\"#tag/Service-Levels\">servicelevels</a>.
    """
    extended_token: NotRequired[str]
    r"""Unique, extended version of the Service Level \"token\".
    Guaranteed to be unique across all Service Levels, and may help offer insight into the specific Service Level it describes.
    """
    parent_servicelevel: NotRequired[ServiceLevelTypedDict]


class ServiceLevelWithParent(BaseModel):
    r"""Contains details regarding the service level for the given rate."""

    name: Optional[str] = None
    r"""Name of the Rate's servicelevel, e.g. `International Priority` or `Standard Post`.
    A servicelevel commonly defines the transit time of a Shipment (e.g., Express vs. Standard), along with other properties.
    These names vary depending on the provider.
    """

    terms: Optional[str] = None
    r"""Further clarification of the service."""

    token: Optional[str] = None
    r"""Token of the Rate's servicelevel, e.g. `usps_priority` or `fedex_ground`.
    See <a href=\"#tag/Service-Levels\">servicelevels</a>.
    """

    extended_token: Optional[str] = None
    r"""Unique, extended version of the Service Level \"token\".
    Guaranteed to be unique across all Service Levels, and may help offer insight into the specific Service Level it describes.
    """

    parent_servicelevel: Optional[ServiceLevel] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["name", "terms", "token", "extended_token", "parent_servicelevel"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
