"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .alcohol import Alcohol, AlcoholTypedDict
from .billing import Billing, BillingTypedDict
from .cod import Cod, CodTypedDict
from .customerreference import CustomerReference, CustomerReferenceTypedDict
from .dangerousgoodsobject import DangerousGoodsObject, DangerousGoodsObjectTypedDict
from .departmentnumber import DepartmentNumber, DepartmentNumberTypedDict
from .dryice import DryIce, DryIceTypedDict
from .insurance import Insurance, InsuranceTypedDict
from .invoicenumber import InvoiceNumber, InvoiceNumberTypedDict
from .ponumber import PoNumber, PoNumberTypedDict
from .rmanumber import RmaNumber, RmaNumberTypedDict
from .shipmentextralasershipattributesenum import ShipmentExtraLasershipAttributesEnum
from .shipmentextrareturnservicetypelasershipenum import (
    ShipmentExtraReturnServiceTypeLasershipEnum,
)
from .shipmentextrareturnservicetypeupsenum import ShipmentExtraReturnServiceTypeUPSEnum
from .upsreferencefields import UPSReferenceFields, UPSReferenceFieldsTypedDict
from enum import Enum
import pydantic
from pydantic import model_serializer
from shippo.types import BaseModel, UNSET_SENTINEL
from typing import List, Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


class AncillaryEndorsement(str, Enum):
    r"""Specify an ancillary service endorsement to provide the USPS with instructions on how to handle undeliverable-as-addressed pieces (DHL eCommerce only)."""

    FORWARDING_SERVICE_REQUESTED = "FORWARDING_SERVICE_REQUESTED"
    RETURN_SERVICE_REQUESTED = "RETURN_SERVICE_REQUESTED"


class DangerousGoodsCode(str, Enum):
    r"""Dangerous Goods Code (DHL eCommerce only). See <a href=\"https://api-legacy.dhlecs.com/docs/v2/appendix.html#dangerous-goods\">Category Codes</a>"""

    ONE = "01"
    TWO = "02"
    THREE = "03"
    FOUR = "04"
    FIVE = "05"
    SIX = "06"
    SEVEN = "07"
    EIGHT = "08"
    NINE = "09"


class PreferredDeliveryTimeframe(str, Enum):
    r"""Required for DHL Germany Paket Sameday. Designates a desired timeframe for delivery. Format is `HHMMHHMM`"""

    TEN_MILLION_ONE_THOUSAND_TWO_HUNDRED = "10001200"
    TWELVE_MILLION_ONE_THOUSAND_FOUR_HUNDRED = "12001400"
    FOURTEEN_MILLION_ONE_THOUSAND_SIX_HUNDRED = "14001600"
    SIXTEEN_MILLION_ONE_THOUSAND_EIGHT_HUNDRED = "16001800"
    EIGHTEEN_MILLION_TWO_THOUSAND = "18002000"
    NINETEEN_MILLION_TWO_THOUSAND_ONE_HUNDRED = "19002100"


ReturnServiceTypeTypedDict = TypeAliasType(
    "ReturnServiceTypeTypedDict",
    Union[
        ShipmentExtraReturnServiceTypeUPSEnum,
        ShipmentExtraReturnServiceTypeLasershipEnum,
    ],
)
r"""Request additional return option for return shipments (UPS and Lasership only)."""


ReturnServiceType = TypeAliasType(
    "ReturnServiceType",
    Union[
        ShipmentExtraReturnServiceTypeUPSEnum,
        ShipmentExtraReturnServiceTypeLasershipEnum,
    ],
)
r"""Request additional return option for return shipments (UPS and Lasership only)."""


class SignatureConfirmation(str, Enum):
    r"""Request standard or adult signature confirmation. You can alternatively request Certified Mail (USPS only)
    or Indirect signature (FedEx only) or Carrier Confirmation (Deutsche Post only).
    """

    STANDARD = "STANDARD"
    ADULT = "ADULT"
    CERTIFIED = "CERTIFIED"
    INDIRECT = "INDIRECT"
    CARRIER_CONFIRMATION = "CARRIER_CONFIRMATION"


class ShipmentExtraTypedDict(TypedDict):
    r"""An object holding optional extra services to be requested."""

    accounts_receivable_customer_account: NotRequired[UPSReferenceFieldsTypedDict]
    alcohol: NotRequired[AlcoholTypedDict]
    r"""Indicates that a shipment contains Alcohol (Fedex and UPS only)."""
    ancillary_endorsement: NotRequired[AncillaryEndorsement]
    r"""Specify an ancillary service endorsement to provide the USPS with instructions on how to handle undeliverable-as-addressed pieces (DHL eCommerce only)."""
    appropriation_number: NotRequired[UPSReferenceFieldsTypedDict]
    authority_to_leave: NotRequired[bool]
    r"""Request `true` to give carrier permission to leave the parcel in a safe place if no one answers the
    door (where supported). When set to `false`, if no one is available to receive the item, the parcel
    will not be left (*surcharges may be applicable).
    """
    bill_of_lading_number: NotRequired[UPSReferenceFieldsTypedDict]
    billing: NotRequired[BillingTypedDict]
    r"""Specify billing details (UPS, FedEx, and DHL Germany only)."""
    bypass_address_validation: NotRequired[bool]
    r"""Bypasses address validation (USPS, UPS, & LaserShip only)."""
    carbon_neutral: NotRequired[bool]
    r"""Request carbon offsets by passing true (UPS only)."""
    carrier_hub_id: NotRequired[str]
    r"""Identifies the carrier injection site."""
    carrier_hub_travel_time: NotRequired[int]
    r"""Travel time in hours from fulfillment center to carrier injection site."""
    cod: NotRequired[CodTypedDict]
    r"""Specify collection on delivery details (UPS only)."""
    cod_number: NotRequired[UPSReferenceFieldsTypedDict]
    container_type: NotRequired[str]
    r"""Specify container type."""
    critical_pull_time: NotRequired[str]
    r"""Carrier arrival time to pickup packages from the fulfillment center.
    UTC format: `%Y-%m-%dT%H:%M:%SZ`
    """
    customer_branch: NotRequired[str]
    r"""Specify customer branch (Lasership only)."""
    customer_reference: NotRequired[CustomerReferenceTypedDict]
    r"""Specify the reference field on the label (FedEx and UPS only)."""
    dangerous_goods: NotRequired[DangerousGoodsObjectTypedDict]
    r"""Container for specifying the presence of dangerous materials. This is specific to USPS, and if any contents
    are provided, only certain USPS service levels will be eligible. For more information, see our
    <a href=\"https://docs.goshippo.com/docs/shipments/hazmat/\">guide on hazardous or dangerous materials shipping</a>.
    """
    dangerous_goods_code: NotRequired[DangerousGoodsCode]
    r"""Dangerous Goods Code (DHL eCommerce only). See <a href=\"https://api-legacy.dhlecs.com/docs/v2/appendix.html#dangerous-goods\">Category Codes</a>"""
    dealer_order_number: NotRequired[UPSReferenceFieldsTypedDict]
    delivery_instructions: NotRequired[str]
    r"""Specify delivery instructions. Up to 500 characters. (FedEx and OnTrac only)."""
    dept_number: NotRequired[DepartmentNumberTypedDict]
    r"""Specify the department number field on the label (FedEx and UPS only)."""
    dry_ice: NotRequired[DryIceTypedDict]
    r"""Specify that the package contains Dry Ice (FedEx, Veho, and UPS only)."""
    fda_product_code: NotRequired[UPSReferenceFieldsTypedDict]
    fulfillment_center: NotRequired[str]
    r"""The fulfilment center where the package originates from."""
    insurance: NotRequired[InsuranceTypedDict]
    r"""To add 3rd party insurance powered by <a href=\"https://docs.goshippo.com/docs/shipments/shippinginsurance/\">XCover</a>,
    specify <br> `amount`, `content`, and `currency`. <br> Alternatively, you can choose carrier provided insurance
    by additionally specifying `provider` (UPS, FedEx and OnTrac only). <br><br> If you do not want to add insurance
    to your shipment, do not set these parameters.
    """
    invoice_number: NotRequired[InvoiceNumberTypedDict]
    r"""Specify the invoice number field on the label (FedEx and UPS only)."""
    is_return: NotRequired[bool]
    r"""This field specifies if it is a scan-based return shipment. See the <a href=\"https://docs.goshippo.com/docs/shipments/returns/\">Create a return shipment</a> section for more details."""
    lasership_attrs: NotRequired[List[ShipmentExtraLasershipAttributesEnum]]
    r"""Specify Lasership Attributes (Lasership only). Multiple options accepted."""
    lasership_declared_value: NotRequired[str]
    r"""Declared value (Lasership only). Defaults to `50.00`."""
    manifest_number: NotRequired[UPSReferenceFieldsTypedDict]
    model_number: NotRequired[UPSReferenceFieldsTypedDict]
    part_number: NotRequired[UPSReferenceFieldsTypedDict]
    po_number: NotRequired[PoNumberTypedDict]
    r"""Specify the PO number field on the label (FedEx and UPS only)."""
    preferred_delivery_timeframe: NotRequired[PreferredDeliveryTimeframe]
    r"""Required for DHL Germany Paket Sameday. Designates a desired timeframe for delivery. Format is `HHMMHHMM`"""
    premium: NotRequired[bool]
    r"""Add premium service to a shipment (DHL Germany international shipments only)."""
    production_code: NotRequired[UPSReferenceFieldsTypedDict]
    purchase_request_number: NotRequired[UPSReferenceFieldsTypedDict]
    qr_code_requested: NotRequired[bool]
    r"""Request a QR code for a given transaction when creating a shipping label (USPS domestic and Evri UK only)."""
    reference_1: NotRequired[str]
    r"""Optional text to be printed on the shipping label if supported by carrier. Up to 50 characters."""
    reference_2: NotRequired[str]
    r"""Optional text to be printed on the shipping label if supported by carrier. Up to 50 characters. For DHL eCommerce, this field can be used for billing reference."""
    request_retail_rates: NotRequired[bool]
    r"""Returns retail rates instead of account-based rates (UPS and FedEx only)."""
    return_service_type: NotRequired[ReturnServiceTypeTypedDict]
    r"""Request additional return option for return shipments (UPS and Lasership only)."""
    rma_number: NotRequired[RmaNumberTypedDict]
    r"""Specify the RMA number field on the label (FedEx and UPS only)."""
    saturday_delivery: NotRequired[bool]
    r"""Marks shipment as to be delivered on a Saturday."""
    salesperson_number: NotRequired[UPSReferenceFieldsTypedDict]
    serial_number: NotRequired[UPSReferenceFieldsTypedDict]
    signature_confirmation: NotRequired[SignatureConfirmation]
    r"""Request standard or adult signature confirmation. You can alternatively request Certified Mail (USPS only)
    or Indirect signature (FedEx only) or Carrier Confirmation (Deutsche Post only).
    """
    store_number: NotRequired[UPSReferenceFieldsTypedDict]
    transaction_reference_number: NotRequired[UPSReferenceFieldsTypedDict]
    usmca_eligible: NotRequired[bool]
    r"""UPS only. Request USMCA (United States-Mexico-Canada Agreement) preferential tariff treatment.
    When enabled, it includes the USMCA eligibility declaration in customs documentation.

    Supported routes and value limits:
    - USA/Canada → Mexico: ≤ $1,000 USD
    - Canada/Mexico → USA: ≤ $2,500 USD
    - USA/Mexico → Canada: ≤ $3,300 CAD

    Only for declaration-only shipments, full USMCA - FormType 04 (Certificate of Origin) is not supported.
    """


class ShipmentExtra(BaseModel):
    r"""An object holding optional extra services to be requested."""

    accounts_receivable_customer_account: Optional[UPSReferenceFields] = None

    alcohol: Optional[Alcohol] = None
    r"""Indicates that a shipment contains Alcohol (Fedex and UPS only)."""

    ancillary_endorsement: Optional[AncillaryEndorsement] = None
    r"""Specify an ancillary service endorsement to provide the USPS with instructions on how to handle undeliverable-as-addressed pieces (DHL eCommerce only)."""

    appropriation_number: Optional[UPSReferenceFields] = None

    authority_to_leave: Optional[bool] = None
    r"""Request `true` to give carrier permission to leave the parcel in a safe place if no one answers the
    door (where supported). When set to `false`, if no one is available to receive the item, the parcel
    will not be left (*surcharges may be applicable).
    """

    bill_of_lading_number: Optional[UPSReferenceFields] = None

    billing: Optional[Billing] = None
    r"""Specify billing details (UPS, FedEx, and DHL Germany only)."""

    bypass_address_validation: Optional[bool] = None
    r"""Bypasses address validation (USPS, UPS, & LaserShip only)."""

    carbon_neutral: Optional[bool] = None
    r"""Request carbon offsets by passing true (UPS only)."""

    carrier_hub_id: Optional[str] = None
    r"""Identifies the carrier injection site."""

    carrier_hub_travel_time: Optional[int] = None
    r"""Travel time in hours from fulfillment center to carrier injection site."""

    cod: Annotated[Optional[Cod], pydantic.Field(alias="COD")] = None
    r"""Specify collection on delivery details (UPS only)."""

    cod_number: Optional[UPSReferenceFields] = None

    container_type: Optional[str] = None
    r"""Specify container type."""

    critical_pull_time: Optional[str] = None
    r"""Carrier arrival time to pickup packages from the fulfillment center.
    UTC format: `%Y-%m-%dT%H:%M:%SZ`
    """

    customer_branch: Optional[str] = None
    r"""Specify customer branch (Lasership only)."""

    customer_reference: Optional[CustomerReference] = None
    r"""Specify the reference field on the label (FedEx and UPS only)."""

    dangerous_goods: Optional[DangerousGoodsObject] = None
    r"""Container for specifying the presence of dangerous materials. This is specific to USPS, and if any contents
    are provided, only certain USPS service levels will be eligible. For more information, see our
    <a href=\"https://docs.goshippo.com/docs/shipments/hazmat/\">guide on hazardous or dangerous materials shipping</a>.
    """

    dangerous_goods_code: Optional[DangerousGoodsCode] = None
    r"""Dangerous Goods Code (DHL eCommerce only). See <a href=\"https://api-legacy.dhlecs.com/docs/v2/appendix.html#dangerous-goods\">Category Codes</a>"""

    dealer_order_number: Optional[UPSReferenceFields] = None

    delivery_instructions: Optional[str] = None
    r"""Specify delivery instructions. Up to 500 characters. (FedEx and OnTrac only)."""

    dept_number: Optional[DepartmentNumber] = None
    r"""Specify the department number field on the label (FedEx and UPS only)."""

    dry_ice: Optional[DryIce] = None
    r"""Specify that the package contains Dry Ice (FedEx, Veho, and UPS only)."""

    fda_product_code: Optional[UPSReferenceFields] = None

    fulfillment_center: Optional[str] = None
    r"""The fulfilment center where the package originates from."""

    insurance: Optional[Insurance] = None
    r"""To add 3rd party insurance powered by <a href=\"https://docs.goshippo.com/docs/shipments/shippinginsurance/\">XCover</a>,
    specify <br> `amount`, `content`, and `currency`. <br> Alternatively, you can choose carrier provided insurance
    by additionally specifying `provider` (UPS, FedEx and OnTrac only). <br><br> If you do not want to add insurance
    to your shipment, do not set these parameters.
    """

    invoice_number: Optional[InvoiceNumber] = None
    r"""Specify the invoice number field on the label (FedEx and UPS only)."""

    is_return: Optional[bool] = None
    r"""This field specifies if it is a scan-based return shipment. See the <a href=\"https://docs.goshippo.com/docs/shipments/returns/\">Create a return shipment</a> section for more details."""

    lasership_attrs: Optional[List[ShipmentExtraLasershipAttributesEnum]] = None
    r"""Specify Lasership Attributes (Lasership only). Multiple options accepted."""

    lasership_declared_value: Optional[str] = None
    r"""Declared value (Lasership only). Defaults to `50.00`."""

    manifest_number: Optional[UPSReferenceFields] = None

    model_number: Optional[UPSReferenceFields] = None

    part_number: Optional[UPSReferenceFields] = None

    po_number: Optional[PoNumber] = None
    r"""Specify the PO number field on the label (FedEx and UPS only)."""

    preferred_delivery_timeframe: Optional[PreferredDeliveryTimeframe] = None
    r"""Required for DHL Germany Paket Sameday. Designates a desired timeframe for delivery. Format is `HHMMHHMM`"""

    premium: Optional[bool] = None
    r"""Add premium service to a shipment (DHL Germany international shipments only)."""

    production_code: Optional[UPSReferenceFields] = None

    purchase_request_number: Optional[UPSReferenceFields] = None

    qr_code_requested: Optional[bool] = None
    r"""Request a QR code for a given transaction when creating a shipping label (USPS domestic and Evri UK only)."""

    reference_1: Optional[str] = None
    r"""Optional text to be printed on the shipping label if supported by carrier. Up to 50 characters."""

    reference_2: Optional[str] = None
    r"""Optional text to be printed on the shipping label if supported by carrier. Up to 50 characters. For DHL eCommerce, this field can be used for billing reference."""

    request_retail_rates: Optional[bool] = None
    r"""Returns retail rates instead of account-based rates (UPS and FedEx only)."""

    return_service_type: Optional[ReturnServiceType] = None
    r"""Request additional return option for return shipments (UPS and Lasership only)."""

    rma_number: Optional[RmaNumber] = None
    r"""Specify the RMA number field on the label (FedEx and UPS only)."""

    saturday_delivery: Optional[bool] = None
    r"""Marks shipment as to be delivered on a Saturday."""

    salesperson_number: Optional[UPSReferenceFields] = None

    serial_number: Optional[UPSReferenceFields] = None

    signature_confirmation: Optional[SignatureConfirmation] = None
    r"""Request standard or adult signature confirmation. You can alternatively request Certified Mail (USPS only)
    or Indirect signature (FedEx only) or Carrier Confirmation (Deutsche Post only).
    """

    store_number: Optional[UPSReferenceFields] = None

    transaction_reference_number: Optional[UPSReferenceFields] = None

    usmca_eligible: Optional[bool] = None
    r"""UPS only. Request USMCA (United States-Mexico-Canada Agreement) preferential tariff treatment.
    When enabled, it includes the USMCA eligibility declaration in customs documentation.

    Supported routes and value limits:
    - USA/Canada → Mexico: ≤ $1,000 USD
    - Canada/Mexico → USA: ≤ $2,500 USD
    - USA/Mexico → Canada: ≤ $3,300 CAD

    Only for declaration-only shipments, full USMCA - FormType 04 (Certificate of Origin) is not supported.
    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "accounts_receivable_customer_account",
                "alcohol",
                "ancillary_endorsement",
                "appropriation_number",
                "authority_to_leave",
                "bill_of_lading_number",
                "billing",
                "bypass_address_validation",
                "carbon_neutral",
                "carrier_hub_id",
                "carrier_hub_travel_time",
                "COD",
                "cod_number",
                "container_type",
                "critical_pull_time",
                "customer_branch",
                "customer_reference",
                "dangerous_goods",
                "dangerous_goods_code",
                "dealer_order_number",
                "delivery_instructions",
                "dept_number",
                "dry_ice",
                "fda_product_code",
                "fulfillment_center",
                "insurance",
                "invoice_number",
                "is_return",
                "lasership_attrs",
                "lasership_declared_value",
                "manifest_number",
                "model_number",
                "part_number",
                "po_number",
                "preferred_delivery_timeframe",
                "premium",
                "production_code",
                "purchase_request_number",
                "qr_code_requested",
                "reference_1",
                "reference_2",
                "request_retail_rates",
                "return_service_type",
                "rma_number",
                "saturday_delivery",
                "salesperson_number",
                "serial_number",
                "signature_confirmation",
                "store_number",
                "transaction_reference_number",
                "usmca_eligible",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
