"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from .userparceltemplate import UserParcelTemplate, UserParcelTemplateTypedDict
from shippo.types import BaseModel
from typing import List, Optional, TypedDict
from typing_extensions import NotRequired


class UserParcelTemplateListTypedDict(TypedDict):
    results: NotRequired[List[UserParcelTemplateTypedDict]]
    

class UserParcelTemplateList(BaseModel):
    results: Optional[List[UserParcelTemplate]] = None
    
