"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .weightunitenum import WeightUnitEnum
from pydantic import model_serializer
from shippo.types import BaseModel, UNSET_SENTINEL
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class UserParcelTemplateWithCarrierTemplateCreateRequestTypedDict(TypedDict):
    template: NotRequired[str]
    r"""The object representing the carrier parcel template"""
    weight: NotRequired[str]
    r"""The weight of the package, in units specified by the weight_unit attribute."""
    weight_unit: NotRequired[WeightUnitEnum]
    r"""The unit used for weight."""


class UserParcelTemplateWithCarrierTemplateCreateRequest(BaseModel):
    template: Optional[str] = None
    r"""The object representing the carrier parcel template"""

    weight: Optional[str] = None
    r"""The weight of the package, in units specified by the weight_unit attribute."""

    weight_unit: Optional[WeightUnitEnum] = None
    r"""The unit used for weight."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["template", "weight", "weight_unit"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
