"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from .webhookeventtypeenum import WebhookEventTypeEnum
from shippo.types import BaseModel
from typing import Optional, TypedDict
from typing_extensions import NotRequired


class WebhookPayloadBatchTypedDict(TypedDict):
    r"""Content of the webhook posted to the external URL"""
    
    event: NotRequired[WebhookEventTypeEnum]
    r"""Type of event that triggered the webhook."""
    test: NotRequired[bool]
    r"""Determines whether the webhook is a test webhook or not."""
    data: NotRequired[str]
    r"""A string containing the batch object ID, of the form 'batch {batchId} (created|processing complete)'."""
    

class WebhookPayloadBatch(BaseModel):
    r"""Content of the webhook posted to the external URL"""
    
    event: Optional[WebhookEventTypeEnum] = None
    r"""Type of event that triggered the webhook."""
    test: Optional[bool] = None
    r"""Determines whether the webhook is a test webhook or not."""
    data: Optional[str] = None
    r"""A string containing the batch object ID, of the form 'batch {batchId} (created|processing complete)'."""
    
