"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .webhookpayloadbatch import WebhookPayloadBatch, WebhookPayloadBatchTypedDict
from .webhookpayloadtrack import WebhookPayloadTrack, WebhookPayloadTrackTypedDict
from .webhookpayloadtransaction import (
    WebhookPayloadTransaction,
    WebhookPayloadTransactionTypedDict,
)
from pydantic import Discriminator, Tag
from shippo.utils import get_discriminator
from typing import Union
from typing_extensions import Annotated, TypeAliasType


WebhookPayloadTypedDict = TypeAliasType(
    "WebhookPayloadTypedDict",
    Union[
        WebhookPayloadTrackTypedDict,
        WebhookPayloadBatchTypedDict,
        WebhookPayloadTransactionTypedDict,
    ],
)
r"""The payload is the body of the POST request Shippo sends to the URL specified at the time of webhook registration."""


WebhookPayload = Annotated[
    Union[
        Annotated[WebhookPayloadTrack, Tag("track_updated")],
        Annotated[WebhookPayloadBatch, Tag("batch_created")],
        Annotated[WebhookPayloadBatch, Tag("batch_purchased")],
        Annotated[WebhookPayloadTransaction, Tag("transaction_created")],
        Annotated[WebhookPayloadTransaction, Tag("transaction_updated")],
    ],
    Discriminator(lambda m: get_discriminator(m, "event", "event")),
]
r"""The payload is the body of the POST request Shippo sends to the URL specified at the time of webhook registration."""
